name: dbt-junitxml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry coverage pytest click
        pip install .[tests]
        poetry install

    - name: Run tests
      run: |
        cd src
        coverage run --source=. -m pytest ../tests
